# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
categories:
  - name: core_infra
    groupThreshold: 0.8
    tests:
    - "Release Nightly Snapshot Python" 
    - "Rotate Metrics Cluster Credentials" 
    - "Community Metrics Prober" 
    - "Publish Docker Snapshots" 
    - "Clean Up GCP Resources" 
    - "Clean Up Prebuilt SDK Images" 
    - "Rotate IO-Datastores Cluster Credentials" 
    - "Release Nightly Snapshot" 
    - "Mark issue as triaged when assigned" 
    - "PostCommit BeamMetrics Publish" 
    - "PreCommit Community Metrics" 
    - "Beam Metrics Report" 
    - "Build and Version Runner Docker Image" 
    - "PreCommit GHA" 
    - "pr-bot-prs-needing-attention" 
    - "PreCommit RAT" 
    - "Assign or close an issue" 
    - "PostCommit Website Test" 
    - "PostCommit Website Publish" 
    - "PreCommit Website" 
    - "PreCommit Website Stage GCS" 
    - "Cleanup Dataproc Resources" 
    - "PreCommit Whitespace" 
    - "Publish Beam SDK Snapshots" 
    - "Cancel Stale Dataflow Jobs" 
    - "pr-bot-pr-updates" 
    - "pr-bot-new-prs" 
  # Tests we want monitored more closely. Only add suites if you are willing to help keep them green :)
  # Usually will be postcommits since PreCommits are more likely to be noticed.
  - name: important_signals
    tests:
    - "PostCommit Python" 
    - "PostCommit Python Xlang Gcp Direct" 
    - "PreCommit Java Examples Dataflow Java11"
    - "PreCommit Java Examples Dataflow Java17"
    - "PreCommit Java Examples Dataflow Java21"
    - "PreCommit Java Examples Dataflow"
    - "PostCommit Java Examples Dataflow V2"
    - "PostCommit Java ValidatesRunner Dataflow"
    - "PostCommit Java Dataflow V1"
    - "PostCommit Java ValidatesRunner Dataflow Streaming"
    - "PostCommit Java Dataflow V2"
    - "PostCommit Java ValidatesRunner Dataflow V2"
    - "PostCommit Python Arm" 
    - "PostCommit Python Examples Direct" 
    - "PostCommit TransformService Direct" 
  - name: core_java
    tests:
    - "PreCommit SQL Java17"
    - "PreCommit SQL Java11"
    - "LoadTests Java GBK Smoke"
    - "PreCommit Java Amazon-Web-Services IO Direct"
    - "PreCommit Java Amqp IO Direct"
    - "PreCommit Java Amazon-Web-Services2 IO Direct"
    - "PreCommit Java"
    - "PreCommit Java Cassandra IO Direct"
    - "PreCommit Java Azure IO Direct"
    - "PreCommit Java Cdap IO Direct"
    - "PreCommit Java Clickhouse IO Direct"
    - "PreCommit Java Csv IO Direct"
    - "Java Tests"
    - "PostCommit Java Avro Versions"
    - "PreCommit Java Debezium IO Direct"
    - "PreCommit Java File-schema-transform IO Direct"
    - "PostCommit Java"
    - "PreCommit Java GCP IO Direct"
    - "PostCommit Java BigQueryEarlyRollout"
    - "PreCommit Java Google-ads IO Direct"
    - "PreCommit Java HBase IO Direct"
    - "PreCommit Java ElasticSearch IO Direct"
    - "PreCommit Java HCatalog IO Direct"
    - "PreCommit Java Hadoop IO Direct"
    - "PreCommit Java IOs Direct"
    - "PostCommit Java Hadoop Versions"
    - "PreCommit Java Jms IO Direct"
    - "PostCommit Java ValidatesRunner Direct JavaVersions"
    - "PreCommit Java Kafka IO Direct"
    - "PostCommit Java Examples Direct"
    - "PreCommit Java JDBC IO Direct"
    - "PostCommit Java ValidatesRunner Samza"
    - "PreCommit Java Mqtt IO Direct"
    - "PreCommit Java Kinesis IO Direct"
    - "PreCommit Java MongoDb IO Direct"
    - "PostCommit Java IO Performance Tests"
    - "PreCommit Java Kudu IO Direct"
    - "PostCommit Java InfluxDbIO Integration Test"
    - "PostCommit Java Jpms Direct Java21"
    - "PostCommit Java ValidatesRunner Twister2"
    - "PreCommit Java Neo4j IO Direct"
    - "PostCommit Java Jpms Direct Java11"
    - "PostCommit Javadoc"
    - "PostCommit Java Jpms Direct Java17"
    - "PreCommit Java Pulsar IO Direct"
    - "PostCommit Java ValidatesRunner ULR"
    - "PreCommit Java Parquet IO Direct"
    - "PreCommit Java Redis IO Direct"
    - "Java JMH"
    - "PreCommit Java RabbitMq IO Direct"
    - "PreCommit Java RequestResponse IO Direct"
    - "PostCommit Java Nexmark Direct"
    - "PreCommit Java Splunk IO Direct"
    - "PreCommit Java Thrift IO Direct"
    - "PreCommit Java Snowflake IO Direct"
    - "PreCommit Java Solr IO Direct"
    - "PostCommit Java PVR Samza"
    - "PreCommit Java Tika IO Direct"
    - "PostCommit Java SingleStoreIO IT"
    - "PostCommit Java Sickbay"
    - "PostCommit Java ValidatesRunner Direct"
    - "PreCommit Java SingleStore IO Direct"
    - "PreCommit Java InfluxDb IO Direct"
    - "PreCommit Kotlin Examples"
  - name: dataflow_java
    tests:
    - "PostCommit XVR GoUsingJava Dataflow"
    - "PostCommit XVR PythonUsingJavaSQL Dataflow"
    - "PostCommit XVR JavaUsingPython Dataflow"
    - "PostCommit XVR PythonUsingJava Dataflow"
    - "PostCommit Java Examples Dataflow ARM"
    - "PostCommit Java ValidatesRunner Dataflow V2 Streaming"
    - "PostCommit Java ValidatesRunner Dataflow JavaVersions"
    - "PostCommit Java Examples Dataflow Java"
    - "PostCommit Java Examples Dataflow V2 Java"
    - "PostCommit Java Jpms Dataflow Java11"
    - "PostCommit Java Jpms Dataflow Java17"
    - "PostCommit Java Nexmark Dataflow"
    - "PostCommit Java Nexmark Dataflow V2"
    - "PostCommit Java Nexmark Dataflow V2 Java"
    - "PostCommit Java Tpcds Dataflow"
  - name: runners_java
    tests:
    - "PostCommit Java PVR Spark3 Streaming"
    - "PostCommit Java ValidatesRunner Spark"
    - "PostCommit Java Examples Spark"
    - "PostCommit Java ValidatesRunner SparkStructuredStreaming"
    - "PostCommit Java ValidatesRunner Spark Java11"
    - "PostCommit Java PVR Spark Batch"
    - "PreCommit Java Spark3 Versions"
    - "PostCommit Java Tpcds Spark"
    - "PostCommit Java Jpms Spark Java11"
    - "PostCommit Java Nexmark Spark"
    - "PostCommit Java Examples Flink"
    - "PostCommit Java Tpcds Flink"
    - "PostCommit Java PVR Flink Streaming"
    - "PostCommit Java Jpms Flink Java11"
    - "PreCommit Java PVR Flink Batch"
    - "PostCommit Java Nexmark Flink"
    - "PreCommit Java PVR Flink Docker"
    - "PreCommit Java Flink Versions"
    - "PostCommit Java ValidatesRunner Flink Java11"
    - "PostCommit Java ValidatesRunner Flink"
  - name: load_perf_java
    tests:
    - "LoadTests Java CoGBK Dataflow Batch"
    - "LoadTests Java CoGBK Dataflow V2 Streaming JavaVersions"
    - "LoadTests Java CoGBK Dataflow Streaming"
    - "LoadTests Java Combine Dataflow Batch"
    - "LoadTests Java Combine Dataflow Streaming"
    - "LoadTests Java CoGBK Dataflow V2 Batch JavaVersions"
    - "LoadTests Java GBK Dataflow Batch"
    - "LoadTests Java GBK Dataflow Streaming"
    - "LoadTests Java GBK Dataflow V2 Batch Java11"
    - "LoadTests Java GBK Dataflow V2 Streaming Java11"
    - "LoadTests Java GBK Dataflow V2 Batch Java17"
    - "LoadTests Java GBK Dataflow V2 Streaming Java17"
    - "LoadTests Java ParDo Dataflow Streaming"
    - "LoadTests Java ParDo Dataflow V2 Streaming JavaVersions"
    - "LoadTests Java ParDo Dataflow V2 Batch JavaVersions"
    - "LoadTests Java ParDo Dataflow Batch"
    - "LoadTests Java ParDo SparkStructuredStreaming Batch"
    - "LoadTests Java CoGBK SparkStructuredStreaming Batch"
    - "LoadTests Java Combine SparkStructuredStreaming Batch"
    - "LoadTests Java GBK SparkStructuredStreaming Batch"
    - "PerformanceTests BigQueryIO Batch Java Avro"
    - "PerformanceTests BigQueryIO Streaming Java"
    - "PerformanceTests BigQueryIO Batch Java Json"
    - "PerformanceTests SQLBigQueryIO Batch Java"
    - "PerformanceTests XmlIOIT"
    - "PostCommit XVR Samza"
    - "PerformanceTests ManyFiles TextIOIT"
    - "PerformanceTests XmlIOIT HDFS"
    - "PerformanceTests ParquetIOIT"
    - "PerformanceTests ParquetIOIT HDFS"
    - "PerformanceTests AvroIOIT"
    - "PerformanceTests ManyFiles TextIOIT HDFS"
    - "PerformanceTests TFRecordIOIT"
    - "PerformanceTests Cdap"
    - "PerformanceTests TextIOIT"
    - "PerformanceTests AvroIOIT HDFS"
    - "PerformanceTests SingleStoreIO"
    - "PerformanceTests SparkReceiver IO"
    - "PerformanceTests Compressed TextIOIT"
    - "PerformanceTests TextIOIT HDFS"
    - "PerformanceTests Compressed TextIOIT HDFS"
    - "PerformanceTests HadoopFormat"
    - "PerformanceTests JDBC"
    - "PerformanceTests Kafka IO"
  - name: core_python
    tests:
    - "Python Dependency Tests" 
    - "PreCommit Python Dataframes" 
    - "PreCommit Python Examples" 
    - "PreCommit Python Integration" 
    - "PostCommit Python ValidatesRunner Samza" 
    - "LoadTests Python Smoke" 
    - "Update Python Depedencies" 
    - "PreCommit Python Runners" 
    - "PreCommit Python Transforms" 
    - "Build python source distribution and wheels" 
    - "Python tests" 
    - "PostCommit Sickbay Python" 
    - "PreCommit Portable Python" 
    - "PreCommit Python Coverage" 
    - "PreCommit Python Docker" 
    - "PreCommit Python" 
    - "PostCommit Python MongoDBIO IT" 
    - "PreCommit Python Docs" 
    - "PreCommit Python Formatter" 
    - "PostCommit Python Nexmark Direct" 
    - "PreCommit Python Lint" 
  - name: runners_python
    tests:
    - "PostCommit Python ValidatesRunner Dataflow" 
    - "Python ValidatesContainer Dataflow ARM" 
    - "PostCommit Python Xlang Gcp Dataflow" 
    - "PostCommit Python Xlang IO Dataflow" 
    - "PostCommit Python Examples Dataflow" 
    - "PostCommit Python ValidatesContainer Dataflow" 
    - "PostCommit Python ValidatesContainer Dataflow With RC" 
    - "PostCommit Python ValidatesRunner Spark" 
    - "PostCommit Python Examples Spark" 
    - "PostCommit Python ValidatesRunner Flink" 
    - "PreCommit Python PVR Flink" 
    - "PostCommit Python Examples Flink" 
  - name: load_perf_python
    tests:
    - "PerformanceTests xlang KafkaIO Python" 
    - "LoadTests Python FnApiRunner Microbenchmark" 
    - "PerformanceTests SpannerIO Write 2GB Python Batch" 
    - "PerformanceTests SpannerIO Read 2GB Python" 
    - "PerformanceTests BiqQueryIO Read Python" 
    - "PerformanceTests BiqQueryIO Write Python Batch" 
    - "PerformanceTests TextIOIT Python" 
    - "PerformanceTests WordCountIT PythonVersions" 
    - "Performance alerting tool on Python load/performance/benchmark tests." 
    - "LoadTests Python SideInput Dataflow Batch" 
    - "LoadTests Python CoGBK Dataflow Batch" 
    - "LoadTests Python CoGBK Dataflow Streaming" 
    - "LoadTests Python Combine Dataflow Batch" 
    - "Inference Python Benchmarks Dataflow" 
    - "LoadTests Python Combine Dataflow Streaming" 
    - "LoadTests Python GBK Dataflow Batch" 
    - "LoadTests Python GBK Dataflow Streaming" 
    - "LoadTests Python GBK reiterate Dataflow Batch" 
    - "LoadTests Python GBK reiterate Dataflow Streaming" 
    - "LoadTests Python ParDo Dataflow Streaming" 
    - "CloudML Benchmarks Dataflow" 
    - "LoadTests Python ParDo Dataflow Batch" 
    - "LoadTests Python CoGBK Flink Batch" 
    - "LoadTests Python Combine Flink Batch" 
    - "LoadTests Python Combine Flink Streaming" 
    - "PerformanceTests PubsubIOIT Python Streaming" 
    - "LoadTests Python ParDo Flink Batch" 
    - "LoadTests Python ParDo Flink Streaming" 
  - name: go
    tests:
    - "PerformanceTests MongoDBIO IT" 
    - "PreCommit Go" 
    - "PreCommit GoPortable" 
    - "PreCommit GoPrism" 
    - "PostCommit Go VR Samza" 
    - "Go tests" 
    - "PostCommit Go" 
    - "PostCommit Go Dataflow ARM" 
    - "LoadTests Go CoGBK Dataflow Batch" 
    - "LoadTests Go Combine Dataflow Batch" 
    - "LoadTests Go GBK Dataflow Batch" 
    - "LoadTests Go ParDo Dataflow Batch" 
    - "LoadTests Go SideInput Dataflow Batch" 
    - "PostCommit Go VR Spark" 
    - "PostCommit Go VR Flink" 
    - "LoadTests Go CoGBK Flink Batch" 
    - "LoadTests Go Combine Flink Batch" 
    - "LoadTests Go GBK Flink Batch" 
    - "LoadTests Go ParDo Flink Batch" 
    - "LoadTests Go SideInput Flink Batch" 
  - name: misc
    tests:
    - "Tour of Beam Go integration tests" 
    - "Tour of Beam Go unittests" 
    - "Tour Of Beam Frontend Test" 
    - "PostCommit XVR Spark3" 
    - "TypeScript Tests" 
    - "Playground Frontend Test" 
    - "PostCommit PortableJar Flink" 
    - "PostCommit SQL" 
    - "Cancel" 
    - "PostCommit PortableJar Spark" 
    - "PreCommit Integration and Load Test Framework" 
    - "pr-bot-update-reviewers" 
    - "Cut Release Branch" 
    - "Generate issue report" 
    - "Dask Runner Tests" 
    - "PreCommit Typescript" 
    - "PostCommit XVR Direct" 
    - "Mark and close stale pull requests" 
    - "PostCommit XVR Flink" 
    - "IssueTagger" 
    - "Assign Milestone on issue close" 
    - "Local environment tests" 
    - "PreCommit SQL" 
    - "LabelPrs" 
    - "build_release_candidate" 

