version: '3'
services:
  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    container_name: beampostgresql
    volumes:
      - beam-postgresql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSGRES_PASSWORD=<PGPasswordHere>
      - POSTGRES_DB=beam_metrics
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    container_name: beamgrafana
    volumes:
      - beam-grafana-libdata:/var/lib/grafana
      - beam-grafana-etcdata:/etc/grafana
      - beam-grafana-logdata:/var/log/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=<GrafanaPasswordHere>
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Beam
      - GF_INSTALL_PLUGINS=vonage-status-panel
volumes:
  beam-postgresql-data:
  beam-grafana-libdata:
  beam-grafana-etcdata:
  beam-grafana-logdata:

