apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: memsqlclusters.memsql.com
spec:
  group: memsql.com
  names:
    kind: MemsqlCluster
    listKind: MemsqlClusterList
    plural: memsqlclusters
    singular: memsqlcluster
    shortNames:
      - singlestore
      - singlestoredb
      - memsql
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: Schema for the SingleStoreDB Cluster
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: Spec defines the desired state of Cluster
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              description: Status defines the observed state of Cluster
              type: object
              x-kubernetes-preserve-unknown-fields: true
          type: object
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Aggregators
          type: integer
          description: Number of Aggregators
          jsonPath: .status.expectedAggregators
        - name: Leaves
          type: integer
          description: Number of Leaf Nodes (per availability group)
          jsonPath: .status.expectedLeaves
        - name: Redundancy Level
          type: integer
          description: Redundancy level of the Cluster
          jsonPath: .spec.redundancyLevel
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
