# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: PostCommit Java IO Performance Tests

on:
  issue_comment:
    types: [created]
  schedule:
  - cron: '0 4/6 * * *'
  pull_request_target:
    paths: ['release/trigger_all_tests.json', '.github/trigger_files/beam_PostCommit_Java_IO_Performance_Tests.json']
  workflow_dispatch:

#Setting explicit permissions for the action to avoid the default permissions which are `write-all` in case of pull_request_target event
permissions:
  actions: write
  pull-requests: write
  checks: write
  contents: read
  deployments: read
  id-token: none
  issues: write
  discussions: read
  packages: read
  pages: read
  repository-projects: read
  security-events: read
  statuses: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.issue.number || github.sha || github.head_ref || github.ref }}-${{ github.event.schedule || github.event.comment.id || github.event.sender.login }}'
  cancel-in-progress: true

env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}

jobs:
  beam_PostCommit_Java_IO_Performance_Tests:
    if: |
      github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'pull_request_target' ||
      (github.event_name == 'schedule' && github.repository == 'apache/beam') ||
      github.event.comment.body == 'Run Java PostCommit IO Performance Tests'
    runs-on: [self-hosted, ubuntu-20.04, main]
    name: ${{ matrix.job_name }} (${{ matrix.job_phrase }} ${{ matrix.test_case }})
    strategy:
      matrix:
        job_name: ["beam_PostCommit_Java_IO_Performance_Tests"]
        job_phrase: ["Run Java PostCommit IO Performance Tests"]
        test_case: ["GCSPerformanceTest", "BigTablePerformanceTest", "BigQueryStorageApiStreamingPerformanceTest"]
    steps:
    - uses: actions/checkout@v4
    - name: Setup repository
      uses: ./.github/actions/setup-action
      with:
        comment_phrase: ${{ matrix.job_phrase }} ${{ matrix.test_case }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        github_job: ${{ matrix.job_name }} (${{ matrix.job_phrase }} ${{ matrix.test_case }})
    - name: Get Beam latest release
      if: github.event_name == 'schedule' #This has scheduled runs run against the latest release
      run: |
        BEAM_VERSION=$(curl -s https://api.github.com/repos/apache/beam/releases/latest | jq -r '.tag_name')
        echo "BEAM_VERSION=${BEAM_VERSION}" >> $GITHUB_ENV
    - name: Checkout release branch
      if: github.event_name == 'schedule' #This has scheduled runs run against the latest release
      uses: actions/checkout@v4
      with:
        ref: ${{ env.BEAM_VERSION }}
        repository: apache/beam
    - name: Setup environment
      uses: ./.github/actions/setup-environment-action
      with:
        java-version: default
    - name: Authenticate on GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    - name: run scheduled javaPostcommitIOPerformanceTests script
      if: github.event_name == 'schedule' #This ensures only scheduled runs publish metrics publicly by changing which exportTable is configured
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        gradle-command: :it:${{ matrix.test_case }}  -DmaxNumWorkers=10
      env:
        exportDataset: performance_tests
        exportTable: io_performance_metrics
    - name: run triggered javaPostcommitIOPerformanceTests script
      if: github.event_name != 'schedule'
      uses: ./.github/actions/gradle-command-self-hosted-action
      with:
        gradle-command: :it:${{ matrix.test_case }}  -DmaxNumWorkers=10
      env:
        exportDataset: performance_tests
        exportTable: io_performance_metrics_test
    - name: Archive JUnit Test Results
      uses: actions/upload-artifact@v4
      if: ${{ !success() }}
      with:
        name: JUnit Test Results
        path: "**/build/reports/tests/"
    - name: Publish JUnit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        commit: '${{ env.prsha || env.GITHUB_SHA }}'
        comment_mode: ${{ github.event_name == 'issue_comment'  && 'always' || 'off' }}
        files: '**/build/test-results/**/*.xml'
