name: beam_PreCommit_Whitespace

on:
  push:
    tags: ['v*']
    branches: ['master', 'release-*']
  pull_request:
    branches: ['master', 'release-*']
    paths: ['*.md', '*.build.gradle']
  issue_comment:
    types: [created]
  schedule:
    - cron: '* */6 * * *'

jobs:
    beam_PreCommit_Whitespace:
        if: ${{github.event.issue.pull_request}} || ${{github.event.comment.body == 'Run Whitespace PreCommit'}} || ${{github.event.schedule}}
        runs-on: [self-hosted, ubuntu-20.04]
        name: beam_PreCommit_Whitespace
        steps:       
          - name: Git checkout
            uses: actions/checkout@v3
          - name: Install Java
            uses: actions/setup-java@v3.8.0
            with:
              distribution: 'zulu'
              java-version: '8'
          - name: Install Python
            uses: actions/setup-python@v4
            with:
              python-version: '3.8'
          - name: Setup Gradle
            uses: gradle/gradle-build-action@v2
            with:
              cache-read-only: false
          - name: run whitespacePreCommit script
            run: ./gradlew :whitespacePreCommit