# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Load Tests CoGBK Flink Batch Go

on:
  issue_comment:
    types: [created]
  schedule:
    - cron: '10 14 * * *'
  workflow_dispatch:

#Setting explicit permissions for the action to avoid the default permissions which are `write-all` in case of pull_request_target event
permissions:
  actions: write
  pull-requests: read
  checks: read
  contents: read
  deployments: read
  id-token: none
  issues: read
  discussions: read
  packages: read
  pages: read
  repository-projects: read
  security-events: read
  statuses: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.issue.number || github.sha || github.head_ref || github.ref }}-${{ github.event.schedule || github.event.comment.body || github.event.sender.login }}'
  cancel-in-progress: true

env:
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
  GCLOUD_ZONE: us-central1-a
  CLUSTER_NAME: beam-loadtests-go-cogbk-flink-batch-${{ github.run_id }}
  GCS_BUCKET: gs://beam-flink-cluster
  FLINK_DOWNLOAD_URL: https://archive.apache.org/dist/flink/flink-1.15.0/flink-1.15.0-bin-scala_2.12.tgz
  HADOOP_DOWNLOAD_URL: https://repo.maven.apache.org/maven2/org/apache/flink/flink-shaded-hadoop-2-uber/2.8.3-10.0/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar
  FLINK_TASKMANAGER_SLOTS: 1
  DETACHED_MODE: true
  HARNESS_IMAGES_TO_PULL: gcr.io/apache-beam-testing/beam-sdk/beam_go_sdk:latest
  JOB_SERVER_IMAGE: gcr.io/apache-beam-testing/beam_portability/beam_flink1.15_job_server:latest
  ARTIFACTS_DIR: gs://beam-flink-cluster/beam-loadtests-go-cogbk-flink-batch-${{ github.run_id }}

jobs:
  beam_LoadTests_Go_CoGBK_Flink_Batch:
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'schedule' ||
      github.event.comment.body == 'Run Load Tests Go CoGBK Flink Batch'
    runs-on: [self-hosted, ubuntu-20.04, main]
    timeout-minutes: 720
    name: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
    strategy:
      matrix:
        job_name: ["beam_LoadTests_Go_CoGBK_Flink_Batch"]
        job_phrase: ["Run Load Tests Go CoGBK Flink Batch"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup repository
        uses: ./.github/actions/setup-action
        with:
          comment_phrase: ${{ matrix.job_phrase }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_job: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
      - name: Prepare test arguments
        uses: ./.github/actions/test-arguments-action
        with:
          test-type: load
          test-language: go
          argument-file-paths: |
            ${{ github.workspace }}/.github/workflows/load-tests-job-configs/config_CoGBK_Go_Batch_Flink_MultipleKey.txt
            ${{ github.workspace }}/.github/workflows/load-tests-job-configs/config_CoGBK_Go_Batch_Flink_Reiteration_10KB.txt
            ${{ github.workspace }}/.github/workflows/load-tests-job-configs/config_CoGBK_Go_Batch_Flink_Reiteration_2MB.txt
          arguments: |
            --job_name=load-tests-go-flink-batch-cogbk-$(date '+%m%d%H%M%S' --utc)
      - name: Start Flink with parallelism 5
        env:
          FLINK_NUM_WORKERS: 5
        run: |
          cd ./.test-infra/dataproc; ./flink_cluster.sh create
      - name: run CoGBK Flink Batch Go Load Test 1 (multiple keys)
        timeout-minutes: 240
        uses: ./.github/actions/gradle-command-self-hosted-action
        with:
          gradle-command: :sdks:go:test:load:run
          arguments: |
            -PloadTest.mainClass=cogbk \
            -Prunner=FlinkRunner \
            '-PloadTest.args=${{ env.beam_LoadTests_Go_CoGBK_Flink_Batch_test_arguments_1 }}' \
      - name: run CoGBK Flink Batch Go Load Test 2 (reiterate 4 times 10KB values)
        timeout-minutes: 240
        uses: ./.github/actions/gradle-command-self-hosted-action
        with:
          gradle-command: :sdks:go:test:load:run
          arguments: |
            -PloadTest.mainClass=cogbk \
            -Prunner=FlinkRunner \
            '-PloadTest.args=${{ env.beam_LoadTests_Go_CoGBK_Flink_Batch_test_arguments_2 }}' \
      - name: run CoGBK Flink Batch Go Load Test 3 (reiterate 4 times 2MB values)
        timeout-minutes: 240
        uses: ./.github/actions/gradle-command-self-hosted-action
        with:
          gradle-command: :sdks:go:test:load:run
          arguments: |
            -PloadTest.mainClass=cogbk \
            -Prunner=FlinkRunner \
            '-PloadTest.args=${{ env.beam_LoadTests_Go_CoGBK_Flink_Batch_test_arguments_3 }}'
      - name: Teardown Flink
        if: always()
        run: |
          ./.test-infra/dataproc/flink_cluster.sh delete