name: beam_PreCommit_Go

on:
  push:
    tags: ['v*']
    branches: ['master', 'release-*']
  pull_request:
    branches: ['master']
    paths: ['model/**', 'sdks/go.**', 'release/**']
  issue_comment:
    types: [created]
  # schedule:
  #   - cron: '* */6 * * *'

jobs:
  beam_PreCommit_Go:
        if: ${{github.event.issue.pull_request}} || ${{github.event.comment.body == 'Run Go PreCommit'}} || ${{github.event.schedule}}
        runs-on: [self-hosted, ubuntu-20.04]
        name: beam_PreCommit_Go
        steps:       
          - name: Git checkout
            uses: actions/checkout@v3
          - name: Install Java
            uses: actions/setup-java@v3.8.0
            with:
              distribution: 'zulu'
              java-version: '8'
          - name: Install Go
            uses: actions/setup-go@v4
            with:
              go-version: '1.20'
          - name: Setup Gradle
            uses: gradle/gradle-build-action@v2
            with:
              cache-read-only: false
          - name: run goPreCommit script
            run: ./gradlew :goPreCommit
