#COMMENT TEST 2
name: vdjerek_testing
on:
  pull_request:
    branches: ['master']
  issue_comment:
    types: [created, edited]

jobs:
  beam_PreCommit_Go:
        runs-on: [self-hosted, ubuntu-20.04, vdjerek-test]
        name: beam_PreCommit_Go
        steps:       
          - name: Git checkout
            uses: actions/checkout@v3
          - name: Install Java
            uses: actions/setup-java@v3.8.0
            with:
              distribution: 'zulu'
              java-version: '8'
          - name: Setup Gradle
            uses: gradle/gradle-build-action@v2
            with:
              cache-read-only: false
          - name: run goPreCommit script
            run: ./gradlew :goPreCommit