# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: PreCommit Python

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'
  push:
    branches: ['master', 'release-*', 'sharding-precommit-python']
    tags: 'v*'
  pull_request_target:
    branches: [ 'master', 'release-*']
    tags: 'v*'
    paths:
      - 'sdks/python/apache_beam/**'
      - 'sdks/python/apache_beam/coders/**'
      - 'sdks/python/apache_beam/internal/**'
      - 'sdks/python/apache_beam/io/concat_source_test.py'
      - 'sdks/python/apache_beam/io/external/generate_sequence_test.py'
      - 'sdks/python/apache_beam/io/hadoopfilesystem_test.py'
      - 'sdks/python/apache_beam/io/iobase_test.py'
      - 'sdks/python/apache_beam/io/range_trackers_test.py'
      - 'sdks/python/apache_beam/io/restriction_trackers_test.py'
      - 'sdks/python/apache_beam/io/source_test_utils_test.py'
      - 'sdks/python/apache_beam/io/sources_test.py'
      - 'sdks/python/apache_beam/io/utils_test.py'
      - 'sdks/python/apache_beam/io/watermark_estimators_test.py'
      - 'sdks/python/apache_beam/metrics/**'
      - 'sdks/python/apache_beam/options/**'
      - 'sdks/python/apache_beam/runners/common_test.py'
      - 'sdks/python/apache_beam/runners/pipeline_context_test.py'
      - 'sdks/python/apache_beam/runners/portability/artifact_service_test.py'
      - 'sdks/python/apache_beam/runners/portability/fn_api_runner/**'
      - 'sdks/python/apache_beam/runners/portability/job_server_test.py'
      - 'sdks/python/apache_beam/runners/portability/local_job_service_test.py'
      - 'sdks/python/apache_beam/runners/portability/portable_runner_test.py'
      - 'sdks/python/apache_beam/runners/portability/sdk_container_builder_test.py'
      - 'sdks/python/apache_beam/runners/portability/stager_test.py'
      - 'sdks/python/apache_beam/runners/runner_test.py'
      - 'sdks/python/apache_beam/runners/sdf_utils_test.py'
      - 'sdks/python/apache_beam/runners/worker/**'
      - 'sdks/python/apache_beam/testing/**'
      - 'sdks/python/apache_beam/tools/microbenchmarks_test.py'
      - 'sdks/python/apache_beam/transforms/**'
      - 'sdks/python/apache_beam/typehints/**'
      - 'sdks/python/apache_beam/utils/**'
permissions: read-all

jobs:
  set-properties:
    runs-on: [self-hosted, ubuntu-20.04]
    outputs:
      properties: ${{ steps.test-properties.outputs.properties }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false
      - id: test-properties
        uses: ./.github/actions/setup-default-test-properties

  apache-beam:
    needs: set-properties
    name: Run Apache Beam Tests
    runs-on: [ self-hosted, ubuntu-20.04 ]
    strategy:
      fail-fast: false
      matrix:
        version: ${{fromJson(needs.set-properties.outputs.properties).PythonTestProperties.ALL_SUPPORTED_VERSIONS}}
        tox-env: ${{fromJson(needs.set-properties.outputs.properties).PythonTestProperties.TOX_ENV}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false
      - name: Set python version
        run: echo "PYTHON_VERSION=$(echo ${{ matrix.version }} | sed -e 's/\.//g')" >> $GITHUB_ENV
      - name: Setup environment
        uses: ./.github/actions/setup-self-hosted-action
        with:
          requires-go-18: false
      - name: run apache_beam/pipeline_test.py
        uses: ./.github/actions/gradle-command-self-hosted-action
        with:
          gradle-command: :sdks:python:test-suites:tox:py${{env.PYTHON_VERSION}}:testPy${{env.PYTHON_VERSION}}${{matrix.tox-env}}
          arguments: "-Pposargs=apache_beam/pipeline_test.py"
      - name: run apache_beam/pvalue_test.py
        uses: ./.github/actions/gradle-command-self-hosted-action
        with:
          gradle-command: :sdks:python:test-suites:tox:py${{env.PYTHON_VERSION}}:testPy${{env.PYTHON_VERSION}}${{matrix.tox-env}}
          arguments: "-Pposargs=apache_beam/pvalue_test.py"


#  precommit-python:
#    needs: set-properties
#    name: PreCommit Python
#    runs-on: [self-hosted, ubuntu-20.04]
#    strategy:
#      fail-fast: false
#      matrix:
#        version: ${{fromJson(needs.set-properties.outputs.properties).PythonTestProperties.ALL_SUPPORTED_VERSIONS}}
#        tox-env: ${{fromJson(needs.set-properties.outputs.properties).PythonTestProperties.TOX_ENV}}
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#        with:
#          ref: ${{ github.event.pull_request.head.sha }}
#          persist-credentials: false
#      - name: Set python version
#        run: echo "PYTHON_VERSION=$(echo ${{ matrix.version }} | sed -e 's/\.//g')" >> $GITHUB_ENV
#      - name: Setup environment
#        uses: ./.github/actions/setup-self-hosted-action
#        with:
#          requires-go-18: false
#
#      - name: Run Apache Beam Tests
#        uses: ./.github/actions/gradle-command-self-hosted-action
#        with:
#          gradle-command: :sdks:python:test-suites:tox:py${{env.PYTHON_VERSION}}:testPy${{env.PYTHON_VERSION}}${{matrix.tox-env}}
#          arguments: "-Pposargs=apache_beam/"
#
#      - name: Run Runners Worker Tests
#        uses: ./.github/actions/gradle-command-self-hosted-action
#        with:
#          gradle-command: :sdks:python:test-suites:tox:py${{env.PYTHON_VERSION}}:testPy${{env.PYTHON_VERSION}}${{matrix.tox-env}}
#          arguments: "-Pposargs=apache_beam/runners/worker/"
#
#      - name: Run Testing Tests
#        uses: ./.github/actions/gradle-command-self-hosted-action
#        with:
#          gradle-command: :sdks:python:test-suites:tox:py${{env.PYTHON_VERSION}}:testPy${{env.PYTHON_VERSION}}${{matrix.tox-env}}
#          arguments: "-Pposargs=apache_beam/testing/"
#
#      - name: Run Transform Tests
#        uses: ./.github/actions/gradle-command-self-hosted-action
#        with:
#          gradle-command: :sdks:python:test-suites:tox:py${{env.PYTHON_VERSION}}:testPy${{env.PYTHON_VERSION}}${{matrix.tox-env}}
#          arguments: "-Pposargs=apache_beam/transforms/"
#
#      - name: Run Typehints Tests
#        uses: ./.github/actions/gradle-command-self-hosted-action
#        with:
#          gradle-command: :sdks:python:test-suites:tox:py${{env.PYTHON_VERSION}}:testPy${{env.PYTHON_VERSION}}${{matrix.tox-env}}
#          arguments: "-Pposargs=apache_beam/typehints/"
#
#      - name: Run Utils Tests
#        uses: ./.github/actions/gradle-command-self-hosted-action
#        with:
#          gradle-command: :sdks:python:test-suites:tox:py${{env.PYTHON_VERSION}}:testPy${{env.PYTHON_VERSION}}${{matrix.tox-env}}
#          arguments: "-Pposargs=apache_beam/utils/"
#
#      - name: Run Coders Tests
#        uses: ./.github/actions/gradle-command-self-hosted-action
#        with:
#          gradle-command: :sdks:python:test-suites:tox:py${{env.PYTHON_VERSION}}:testPy${{env.PYTHON_VERSION}}${{matrix.tox-env}}
#          arguments: "-Pposargs=apache_beam/coders/"
#
#      - name: Run Internal Tests
#        uses: ./.github/actions/gradle-command-self-hosted-action
#        with:
#          gradle-command: :sdks:python:test-suites:tox:py${{env.PYTHON_VERSION}}:testPy${{env.PYTHON_VERSION}}${{matrix.tox-env}}
#          arguments: "-Pposargs=apache_beam/internal/"
#
#      - name: Run Metrics Tests
#        uses: ./.github/actions/gradle-command-self-hosted-action
#        with:
#          gradle-command: :sdks:python:test-suites:tox:py${{env.PYTHON_VERSION}}:testPy${{env.PYTHON_VERSION}}${{matrix.tox-env}}
#          arguments: "-Pposargs=apache_beam/metrics/"
#
#      - name: Run Options Tests
#        uses: ./.github/actions/gradle-command-self-hosted-action
#        with:
#          gradle-command: :sdks:python:test-suites:tox:py${{env.PYTHON_VERSION}}:testPy${{env.PYTHON_VERSION}}${{matrix.tox-env}}
#          arguments: "-Pposargs=apache_beam/options/"
#
#      - name: Run Runners Portability FnApiRunner Tests
#        uses: ./.github/actions/gradle-command-self-hosted-action
#        with:
#          gradle-command: :sdks:python:test-suites:tox:py${{env.PYTHON_VERSION}}:testPy${{env.PYTHON_VERSION}}${{matrix.tox-env}}
#          arguments: "-Pposargs=apache_beam/runners/portability/fn_api_runner/"
#      - name: Run Runners Portability Stager Test
#        uses: ./.github/actions/gradle-command-self-hosted-action
#        with:
#          gradle-command: :sdks:python:test-suites:tox:py${{env.PYTHON_VERSION}}:testPy${{env.PYTHON_VERSION}}${{matrix.tox-env}}
#          arguments: "-Pposargs=apache_beam/runners/portability/stager_test.py"
#      - name: Run Runners Runner Test
#        uses: ./.github/actions/gradle-command-self-hosted-action
#        with:
#          gradle-command: :sdks:python:test-suites:tox:py${{env.PYTHON_VERSION}}:testPy${{env.PYTHON_VERSION}}${{matrix.tox-env}}
#          arguments: "-Pposargs=apache_beam/runners/runner_test.py"
#      - name: Run Runners SDF Utils Test
#        uses: ./.github/actions/gradle-command-self-hosted-action
#        with:
#          gradle-command: :sdks:python:test-suites:tox:py${{env.PYTHON_VERSION}}:testPy${{env.PYTHON_VERSION}}${{matrix.tox-env}}
#          arguments: "-Pposargs=apache_beam/runners/sdf_utils_test.py"
#
#      - name: Run Tools Microbenchmarks Test
#        uses: ./.github/actions/gradle-command-self-hosted-action
#        with:
#          gradle-command: :sdks:python:test-suites:tox:py${{env.PYTHON_VERSION}}:testPy${{env.PYTHON_VERSION}}${{matrix.tox-env}}
#          arguments: "-Pposargs=apache_beam/tools/microbenchmarks_test.py"
#
#      - name: Run IO Concat Source Test
#        uses: ./.github/actions/gradle-command-self-hosted-action
#        with:
#          gradle-command: :sdks:python:test-suites:tox:py${{env.PYTHON_VERSION}}:testPy${{env.PYTHON_VERSION}}${{matrix.tox-env}}
#          arguments: "-Pposargs=apache_beam/io/concat_source_test.py"
#      - name: Run IO External Generate Sequence Test
#        uses: ./.github/actions/gradle-command-self-hosted-action
#        with:
#          gradle-command: :sdks:python:test-suites:tox:py${{env.PYTHON_VERSION}}:testPy${{env.PYTHON_VERSION}}${{matrix.tox-env}}
#          arguments: "-Pposargs=apache_beam/io/external/generate_sequence_test.py"
#      - name: Run IO IOBase Test
#        uses: ./.github/actions/gradle-command-self-hosted-action
#        with:
#          gradle-command: :sdks:python:test-suites:tox:py${{env.PYTHON_VERSION}}:testPy${{env.PYTHON_VERSION}}${{matrix.tox-env}}
#          arguments: "-Pposargs=apache_beam/io/iobase_test.py"
#      - name: Run IO Range Trackers Test
#        uses: ./.github/actions/gradle-command-self-hosted-action
#        with:
#          gradle-command: :sdks:python:test-suites:tox:py${{env.PYTHON_VERSION}}:testPy${{env.PYTHON_VERSION}}${{matrix.tox-env}}
#          arguments: "-Pposargs=apache_beam/io/range_trackers_test.py"
#      - name: Run IO Restrinction Trackers Test
#        uses: ./.github/actions/gradle-command-self-hosted-action
#        with:
#          gradle-command: :sdks:python:test-suites:tox:py${{env.PYTHON_VERSION}}:testPy${{env.PYTHON_VERSION}}${{matrix.tox-env}}
#          arguments: "-Pposargs=apache_beam/io/restriction_trackers_test.py"
#      - name: Run IO Source Test Utils Test
#        uses: ./.github/actions/gradle-command-self-hosted-action
#        with:
#          gradle-command: :sdks:python:test-suites:tox:py${{env.PYTHON_VERSION}}:testPy${{env.PYTHON_VERSION}}${{matrix.tox-env}}
#          arguments: "-Pposargs=apache_beam/io/source_test_utils_test.py"
#      - name: Run IO Sources Test
#        uses: ./.github/actions/gradle-command-self-hosted-action
#        with:
#          gradle-command: :sdks:python:test-suites:tox:py${{env.PYTHON_VERSION}}:testPy${{env.PYTHON_VERSION}}${{matrix.tox-env}}
#          arguments: "-Pposargs=apache_beam/io/sources_test.py"
#      - name: Run IO Utils Test
#        uses: ./.github/actions/gradle-command-self-hosted-action
#        with:
#          gradle-command: :sdks:python:test-suites:tox:py${{env.PYTHON_VERSION}}:testPy${{env.PYTHON_VERSION}}${{matrix.tox-env}}
#          arguments: "-Pposargs=apache_beam/io/utils_test.py"
#      - name: Run IO Watermark Estimators Test
#        uses: ./.github/actions/gradle-command-self-hosted-action
#        with:
#          gradle-command: :sdks:python:test-suites:tox:py${{env.PYTHON_VERSION}}:testPy${{env.PYTHON_VERSION}}${{matrix.tox-env}}
#          arguments: "-Pposargs=apache_beam/io/watermark_estimators_test.py"
#
#      - name: Run Runners Common Test
#        uses: ./.github/actions/gradle-command-self-hosted-action
#        with:
#          gradle-command: :sdks:python:test-suites:tox:py${{env.PYTHON_VERSION}}:testPy${{env.PYTHON_VERSION}}${{matrix.tox-env}}
#          arguments: "-Pposargs=apache_beam/runners/common_test.py"
#      - name: Run Runners Pipeline Context Test
#        uses: ./.github/actions/gradle-command-self-hosted-action
#        with:
#          gradle-command: :sdks:python:test-suites:tox:py${{env.PYTHON_VERSION}}:testPy${{env.PYTHON_VERSION}}${{matrix.tox-env}}
#          arguments: "-Pposargs=apache_beam/runners/pipeline_context_test.py"
#      - name: Run Runners Portability Artifact Service Test
#        uses: ./.github/actions/gradle-command-self-hosted-action
#        with:
#          gradle-command: :sdks:python:test-suites:tox:py${{env.PYTHON_VERSION}}:testPy${{env.PYTHON_VERSION}}${{matrix.tox-env}}
#          arguments: "-Pposargs=apache_beam/runners/portability/artifact_service_test.py"
#
#      - name: Run Runners Portability Job Server Test
#        uses: ./.github/actions/gradle-command-self-hosted-action
#        with:
#          gradle-command: :sdks:python:test-suites:tox:py${{env.PYTHON_VERSION}}:testPy${{env.PYTHON_VERSION}}${{matrix.tox-env}}
#          arguments: "-Pposargs=apache_beam/runners/portability/job_server_test.py"
#      - name: Run Runners Local Job Service Test
#        uses: ./.github/actions/gradle-command-self-hosted-action
#        with:
#          gradle-command: :sdks:python:test-suites:tox:py${{env.PYTHON_VERSION}}:testPy${{env.PYTHON_VERSION}}${{matrix.tox-env}}
#          arguments: "-Pposargs=apache_beam/runners/portability/local_job_service_test.py"
#      - name: Run Runners Portability Portable Runner Test
#        uses: ./.github/actions/gradle-command-self-hosted-action
#        with:
#          gradle-command: :sdks:python:test-suites:tox:py${{env.PYTHON_VERSION}}:testPy${{env.PYTHON_VERSION}}${{matrix.tox-env}}
#          arguments: "-Pposargs=apache_beam/runners/portability/portable_runner_test.py"
#      - name: Run Runners Portability SDK Container Builder Test
#        uses: ./.github/actions/gradle-command-self-hosted-action
#        with:
#          gradle-command: :sdks:python:test-suites:tox:py${{env.PYTHON_VERSION}}:testPy${{env.PYTHON_VERSION}}${{matrix.tox-env}}
#          arguments: "-Pposargs=apache_beam/runners/portability/sdk_container_builder_test.py"
#
#      - name: Run IO Hadoop File System Test
#        uses: ./.github/actions/gradle-command-self-hosted-action
#        with:
#          gradle-command: :sdks:python:test-suites:tox:py${{env.PYTHON_VERSION}}:testPy${{env.PYTHON_VERSION}}${{matrix.tox-env}}
#          arguments: "-Pposargs=apache_beam/io/hadoopfilesystem_test.py"