# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# To learn more about GitHub Actions in Apache Beam check the CI.md

# Runs PostCommit Java Validates Runner Direct on JDK11/17 via cron and on push to master

name: PostCommit Java Validates Runner Direct JDK 11/17

on:
  schedule:
    - cron: '0 */6 * * *'
  push:
    branches: ['master', 'release-*']
    tags: ['v*']
permissions: read-all

jobs:
  set-properties:
    runs-on: self-hosted
    outputs:
      properties: ${{ steps.test-properties.outputs.properties }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: recursive
      - id: test-properties
        uses: ./.github/actions/setup-default-test-properties

  postcommit-java-validates-runner-direct:
    needs: set-properties
    name: Run PostCommit Java Validates Runner Direct JDK 11/17
    runs-on: self-hosted
    strategy:
      fail-fast: true
      matrix:
        java: ${{fromJson(needs.set-properties.outputs.properties).JavaTestProperties.SUPPORTED_VERSIONS}}
        exclude:
          - java: "8" #Execution with JDK8 is performed in another workflow.
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: recursive
      - name: Setup environment
        uses: ./.github/actions/setup-self-hosted-action
      - name: Run :runners:direct-java:shadowJar
        uses: ./.github/actions/gradle-command-self-hosted-action
        with:
          gradle-command: :runners:direct-java:shadowJar
      - name: Run :runners:direct-java:shadowTestJar
        uses: ./.github/actions/gradle-command-self-hosted-action
        with:
          gradle-command: :runners:direct-java:shadowTestJar
      - name: Setup Java ${{ matrix.java }} #Setting up Java 11/17 to execute tests.
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Run :runners:direct-java:validatesRunner in Java-${{ matrix.java }}
        uses: ./.github/actions/gradle-command-self-hosted-action
        with:
          gradle-command: :runners:direct-java:validatesRunner
          arguments: -x shadowJar -x shadowTestJar -x compileJava -x compileTestJava
