<!--
    Licensed to the Apache Software Foundation (ASF) under one
    or more contributor license agreements.  See the NOTICE file
    distributed with this work for additional information
    regarding copyright ownership.  The ASF licenses this file
    to you under the Apache License, Version 2.0 (the
    "License"); you may not use this file except in compliance
    with the License.  You may obtain a copy of the License at
      http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
name: Precommit Python Dataframe
run-name: Python Precommit Dataframe
on:
  pull_request:
    branches: [ "master", "release-*" ]
    paths: [ "model/.*","sdks/python/.*","release/.*"]
  issue_comment:
    types: [created, edited]


jobs:
  PythonDataframe:
    strategy:
      matrix:
        python_version: ['37','38','39','310','311']
    if: ${{github.event.issue.pull_request}} || ${{github.event.comment.body == 'Run Python_Dataframes PreCommit'}} || ${{github.event.schedule == '* */6 * * *'}}
    runs-on: [self-hosted, ubuntu-20.04]
    defaults:
      run:
        working-directory: sdks/python


    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run:  pip install --retries 10 --upgrade pip && ls && pwd && pip install --retries 10 --upgrade tox==3.20.1 -r ./build-requirements.txt
        working-directory: sdks/python
      - name: Run python cloud 
        if: ${{ matrix.python_version  != '38' }}
        run: tox -e py${{ matrix.python_version }}-cloud -- apache_beam/dataframe/ 
        working-directory: sdks/python
      - name: Run mypy
        run: tox -e py${{ matrix.python_version }}-cython -- apache_beam/dataframe/ 
        working-directory: sdks/python
