# To learn more about GitHub Actions in Apache Beam check the CI.md

name: LI Build Python Source Distribution

on:
  push:
    branches: ['li_trunk', 'li-release-*']
    tags: 'v*'
    paths: ['sdks/python/**', 'model/**', 'release/**']

jobs:

  build_source:
    runs-on: ubuntu-latest
    name: Build python source distribution
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Get build dependencies
        working-directory: ./sdks/python
        run: python -m pip install -r build-requirements.txt -r build-requirements-linkedin.txt
      - name: Install build tools
        run: python -m pip install wheel twine setuptools
      - name: Build source
        working-directory: ./sdks/python
        run: python setup.py sdist --formats=zip
      - name: Publish Python Package to LI
        working-directory: ./sdks/python
        run: twine upload dist/*
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          TWINE_USERNAME: ${{ secrets.PYPI_USER }}
