# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# To learn more about GitHub Actions in Apache Beam check the CI.md

name: Tour of Beam Go integration tests

on:
  push:
    branches: ['master', 'release-*']
    tags: 'v*'
    paths: ['learning/tour-of-beam/backend/**']
  pull_request:
    branches: ['master', 'release-*']
    tags: 'v*'
    paths: ['learning/tour-of-beam/backend/**']

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  TOB_LEARNING_ROOT: ./samples/learning-content
  DATASTORE_PROJECT_ID: test-proj
  DATASTORE_EMULATOR_HOST: localhost:8081
  DATASTORE_EMULATOR_DATADIR: ./datadir
  PORT_SDK_LIST: 8801
  PORT_GET_CONTENT_TREE: 8802
  PORT_GET_UNIT_CONTENT: 8803


jobs:
  integration:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./learning/tour-of-beam/backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          # pin to the biggest Go version supported by Cloud Functions runtime
          go-version: '1.16'

      # 1. Datastore emulator
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
        with:
          version: 397.0.0
          project_id: ${{ env.DATASTORE_PROJECT_ID }}
          install_components: 'beta,cloud-datastore-emulator'
      - name: 'Start datastore emulator'
        run: |
          gcloud beta emulators datastore start \
          --data-dir=${{ env.DATASTORE_EMULATOR_DATADIR }} \
          --host-port=${{ env.DATASTORE_EMULATOR_HOST }} \
          --consistency=1 &

      # 2. start function-framework processes in BG
      - name: Compile CF
        run: go build -o ./tob_function cmd/main.go
      - name: Run getSdkList in background
        run: PORT=${{ env.PORT_SDK_LIST }} FUNCTION_TARGET=getSdkList ./tob_function &
      - name: Run getContentTree in background
        run: PORT=${{ env.PORT_GET_CONTENT_TREE }} FUNCTION_TARGET=getContentTree ./tob_function &
      - name: Run getUnitContent in background
        run: PORT=${{ env.PORT_GET_UNIT_CONTENT }} FUNCTION_TARGET=getUnitContent ./tob_function &

      # 3. Load data in datastore: run CD step on samples/learning-content
      - name: Run CI/CD to populate datastore
        run: go run cmd/ci_cd/ci_cd.go

      # 4. Check sdkList, getContentTree, getUnitContent: run integration tests
      - name: Go integration tests
        run: go test -v --tags integration ./integration_tests/...
      # 5. Compare storage/datastore/index.yml VS generated
      - name: Check index.yaml
        run: |
          diff -q "${{ env.DATASTORE_EMULATOR_DATADIR }}/WEB-INF/index.yaml" \
          internal/storage/index.yaml \
          || ( echo "index.yaml mismatch"; exit 1)

